# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Olm24bjNYwcaqJi51VNMx0y8gHknDiYF
"""

import random
print("Welcome to the Game of Rock Paper Scissor")
user_input = input("Type R or P or S for choosing rock, paper and scissor respectively: ").lower()
machine = random.randint(1,3)
if machine==1:
  print("Computer chosen Rock")
elif machine==2:
  print("Computer chosen Paper")
else:
  print("Compueter chosen Scissor")
user = ["r","p","s"].index(user_input) + 1
if user==machine:
    print("It's a draw!")
elif str(user) + str(machine) in ["13", "21", "32"]:
    print("You win!")
else:
    print("You lose.")

